---
- name: enable uwsgi
  systemd:
    name: gunicorn.socket
    state: started
    enabled: yes
- name: restart nginx
  systemd:
    name: nginx
    state: restarted
- name: enable codedeploy
  systemd:
    name: codedeploy-agent
    state: started
    enabled: yes
