---
- name: install python repo
  apt_repository: 
    repo: ppa:deadsnakes/ppa
- name: install python
  apt:
    name: python3.6
    update_cache: yes
- name: Install Python-Dev
  apt:
    name: python3.6-dev
    update_cache: yes
- name: Install Python-Pip
  apt:
    name: python3-pip
    update_cache: yes
- name: Install Build essential
  apt:
    name: build-essential
    update_cache: yes
- name: Install Pipenv
  pip:
    name: pipenv
- name: Pulldown Flask Code
  git:
    repo: '{{ git_repo_url }}'
    dest: '{{ project_dir }}'
  become: no
- name: Install python requirements
  command: chdir={{ project_dir }} pipenv install
  become: no
- name: Create custom fact directory
  file:
    path: /etc/ansible/facts.d
    state: directory
- name: Insert cutom fact file
  copy:
    src: files/venv.fact
    dest: /etc/ansible/facts.d/venv.fact
    mode: 0755
- name: Rerun setup for custom facts
  setup: filter=ansible_local
  become: no
- name: Create uWSGI Service
  template: src=visitly.service.j2 dest=/etc/systemd/system/{{project_name}}.service
  notify: enable uwsgi
- name: Install nginx
  apt: 
    name: nginx 
    update_cache: yes
- name: Set sites available
  template: src=visitly.j2 dest=/etc/nginx/sites-available/visitly
- name: Link sites available
  command: ln -sf /etc/nginx/sites-availalbe/visitly /etc/nginx/sites-enabled
- name: Validate nginx
  command: nginx -t
  notify: restart nginx
- name: Create public html dir
  file:
    path: /var/www/public_html/health/
    state: directory
    owner: www-data
    group: www-data
    mode: 0755
    recurse: yes
- name: Copy health check file over
  copy: 
    src: health.html 
    dest: /var/www/public_html/health/health.html
- name: Copy index file over
  copy: 
    src: health.html 
    dest: /var/www/public_html/health/index.html
- name: Enable firewall
  command: ufw allow 'Nginx Full'
